### ISSUE TITLE
Non-daemon Molr threads preventing application shutdown 

### ISSUE THREAD

**Issue by zanzica** [molr/molr-gui-fx#10]
Hi there,

we have encountered a problem with non-daemon threads started by Molr that prevent our Fx application from terminating if we do not call System.exit (which we would prefer to avoid). We would love to discuss it with you to find a good solution.

### How to reproduce
The problem can be easily reproduced by slightly adapting `MolrFxSupportMinimalDemo`: 

#### Preparation
- Adapt [line 17](https://github.com/molr/molr-gui-fx/blob/master/src/main/java/io/molr/gui/fx/demo/MolrFxSupportMinimalDemo.java#L17) to 
` applicationLauncher().windowCloseHandler(evt -> Platform.exit()).configurationClasses(MolrFxSupportMinimalDemo.class).launch()`
This changes the default window close handler from a `System.exit` call to the `Platform.exit` call which we are using for our application as well. 

- Start the demo application.
- Monitor the application running state and the running threads (e.g. with JConsole or your IDE).
![grafik](https://user-images.githubusercontent.com/14939118/99092518-8550f500-25d1-11eb-8d18-77aea73d65ca.png)

#### Test: Application terminates when Molr UI not openend
- Perform the preparation steps. 
- Without doing anything, close the application again. 
- You should see that the application terminates as expected.
![grafik](https://user-images.githubusercontent.com/14939118/99095012-ddd5c180-25d4-11eb-8b1b-5e317a379f89.png)

####  Test: Application does not terminate when Molr UI openend
- Perform the preparation steps. 
- Click on any debug mission, e.g. "debug stub1". 
- Close the dialog that is opened without doing anything. 
- You should see that several new non-daemon threads have been spawned by Molr.
![grafik](https://user-images.githubusercontent.com/14939118/99093005-39528000-25d2-11eb-8497-9f104c5e4a6e.png)
- Close the application.
- You should see that the application has not terminated. The new threads remain running. Note that the Fx thread is gone, as it has been terminated by `Platform.exit`. Only the non-daemon threads from Molr prevent the Java VM from terminating.
![grafik](https://user-images.githubusercontent.com/14939118/99093119-5be49900-25d2-11eb-9c48-387645aedf20.png)

### Why this is an issue
If the application does not terminate properly, even though the UI has been closed, it quickly creates ugly situations during development when many application instances are still "hanging" in the background.

We would like to avoid calling the hard `System.exit` in our application, as it is possible that a non-daemon thread is still finishing its work and will terminate soon (allowing the VM to terminate as well), and we would not like to suddenly abort such a thread.
However, this does not seem to be the case here for the Molr threads. 

@StefanGsi has pointed out in the past that this should not be an issue if we do not run a MissionExecutor in our app, but use the remote service that will be available in the future. I agree with that, however, we would ideally want to be able to test the Molr UI and the missions (with e.g. a `DoNothingDeviceDriver`) during development, when we have no remote service available.

### Things we tried
We have a hook in our app that is called when the user closes the application. There, we can check which non-daemon threads are still running. However, not only is there no easy way to determine which threads are "Molr threads" and might be safe to terminate, there is also no practical way (that I know of) to terminate a thread from the "outside" - e.g. the `Thread#stop` method is deprecated and causes exceptions to be thrown, etc.

### Solution ideas
- Molr could create daemon threads instead of non-daemon threads. 
- Molr could provide a way for the user to tell it to "terminate" itself and all its threads. Molr should then internally shut down all its executors/threads etc. .

Looking forward to talking about this with you guys! :-)

**Comment by kaifox** [comment]
Actually, this was a bug in molr itself.

https://github.com/molr/molr/pull/75

Thank you @zanzica for the well described issue!

**Comment by zanzica** [comment]
Can confirm as fixed using molr-gui-fx 0.3.8 and molr 0.3.8 !
